### ISSUE TITLE
Service was shut down

### ISSUE THREAD

**Issue by jnv** [tiliado/nuvola-app-this-is-my-jam#4]
Hi @fenryxo, just to let you know, This Is My Jam [ceased operation](http://thisismyjam.tumblr.com/post/126260430022/jam-preserves) and was converted [into an archive](https://www.thisismyjam.com/). It makes no sense to further maintain and ship integration for this service.

**Comment by fenryxo** [comment]
Oh, that's a pity :-( Thanks for the info though, I'll remove Jam from the package repository & the website then. However, I'll keep this Github repository around. Could add a note "**Note:** This Is My Jam [ceased operation](http://thisismyjam.tumblr.com/post/126260430022/jam-preserves) and was converted [into an archive](https://www.thisismyjam.com/)" to README.md?

**Comment by jnv** [comment]
Agreed, thank you. I have added a note to the readme.
